DROP DATABASE IF EXISTS spicydonuts;

CREATE DATABASE spicydonuts;

USE spicydonuts;

DROP TABLE IF EXISTS Survey;
        
CREATE TABLE Survey (
  id INTEGER AUTO_INCREMENT,
  Topic VARCHAR(250) DEFAULT NULL,
  Yes INTEGER DEFAULT NULL,
  No INTEGER DEFAULT NULL,
  Total INTEGER DEFAULT NULL,
  UserId VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
  id INTEGER AUTO_INCREMENT,
  Name VARCHAR(255) DEFAULT NULL,
  Password VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)