DROP DATABASE IF EXISTS spicydonuts;

CREATE DATABASE spicydonuts;

USE spicydonuts;

DROP TABLE IF EXISTS `Survey`;
        
CREATE TABLE `Survey` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `Topic` VARCHAR(250) NULL DEFAULT NULL,
  `Yes` INTEGER(100) NULL DEFAULT NULL,
  `No` INTEGER NULL DEFAULT NULL,
  `Total` INTEGER(100) NULL DEFAULT NULL,
  `UserId` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS 'Users';

CREATE TABLE `Users` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  'Password' VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
)